apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingapi
  template:
    metadata:
      labels:
        app: bookingapi
    spec:
      containers:
      - name: bookingapi
        image: marksantosiress/bookinglist_api:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookingapi-service
spec:
  selector:
    app: bookingapi
  type: NodePort
  ports:
  - name: bookingapi-service
    port: 80
    targetPort: 80
    nodePort: 30032
    protocol: TCP
